baseURL: "https://journal.malinkang.com/"
DefaultContentLanguage: "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode: "zh"
title: "Journal"
copyright: " 2021 malinkang."
theme:
  - "diary"
  - "gallery"
# googleAnalytics: "UA-123-45"

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "perldoc"
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

params:
  subtitle: "过好每一天。"
  enableUtterances: true


module:
  imports:
  - path: github.com/Runzelee/aplayer-hugo-module

# Twitter Card and Open Graph settings
enableOpenGraph: true
enableTwitterCards: true
title: "linkang's life" # will set 'og:site_name'
description: "My HomePage Description"  # will set 'og:description'

params:
  gitalk:
    owner: ""
    repo: ""
    client_id: ""
    client_secret: ""

taxonomies:
  tag: "tags"
  category: "categories"

params:
  utterances:
    repo: "malinkang/note"
    term: "url"
    label: "diary"
    theme: "preferred-color-scheme"

menu:
  main:
    - url: "/categories"
      name: "分类"
      weight: 2
    - url: "/tags"
      name: "标签"
      weight: 3
    - url: "/movies"
      name: "电影"
      weight: 3
    - url: "/books"
      name: "阅读"
      weight: 3
    - url: "/posts"
      name: "归档"
      weight: 1
    - url: "/index.xml"
      name: "RSS Feed"
      weight: 4

params:
  page:
    mapbox:
      accessToken: "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      lightStyle: "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle: "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation: true
      geolocate: true
      scale: true
      fullscreen: true
