baseURL = "https://diary.malinkang.com/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh"
title = "Diary"
copyright = " 2021 malinkang."
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
subtitle = "过好每一天。"
enableUtterances = true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "linkang's life" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = ""
  repo = ""
  client_id = ""
  client_secret = ""
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
  repo="malinkang/note"
  term="url"
  label="diary"
  theme="preferred-color-scheme"

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/movies"
name = "电影"
weight = 3
[[menu.main]]
url = "/books"
name = "阅读"
weight = 3
[[menu.main]]
url = "/posts"
name = "归档"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4

# Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
# Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
[params.page.mapbox]
  # access token of Mapbox GL JS
  # Mapbox GL JS 的 access token
  accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
  # style for the light theme
  # 浅色主题的地图样式
  lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
  # style for the dark theme
  # 深色主题的地图样式
  darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
  # whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
  # 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
  navigation = true
  # whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
  # 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
  geolocate = true
  # whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
  # 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
  scale = true
  # whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
  # 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
  fullscreen = true