baseURL = "https://d-opal.vercel.app/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh"
title = "linkang's life"
copyright = " 2021 malinkang."
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "linkang's life"
enableGitalk = true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "linkang's life" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "malinkang"
  repo = "d"
  client_id = "6ed488cb314d734b8328"
  client_secret = "3b9f3e6685377f0c723a9dd4064b17f034172900"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/posts"
name = "归档"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4