name: Generate Diary

on:
  workflow_dispatch:
    inputs:
      content:
        description: 'content'
        required: false


jobs:
  - name: send telegram message on push
    uses: appleboy/telegram-action@master
    with:
      token: ${{ secrets.TELEGRAM_TOKEN }}
      message: "test"