name: hugo sync
on:
  workflow_dispatch:
    inputs:
      content:
        description: 'content'
        required: false
  schedule:
    - cron: "30 15 * * *"
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: create tomorrow diary 
        run: |
          python scripts/notion/create_diary.py
      - name: ncm sync
        run: |
          python scripts/notion/ncm.py
      - name: bilibili sync
        run: |
          python scripts/notion/bilibili.py       
      - name: toggl
        run: |
          python scripts/notion/toggl.py
      - name: keep
        run: |
          python scripts/notion/keep.py
      - name: memos sync
        run: |
            python scripts/notion/mastodon.py
      - name: duolingo sync
        run: |
          python scripts/notion/duolingo.py
      - name: weread sync
        run: |
          python scripts/notion/weread.py "${{secrets.WEREAD_COOKIE}}"
      - name: hugo sync
        run: |
          python scripts/notion/hugo.py '${{ github.event.inputs.content }}'
      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: malinkang
          author_email: linkang.ma@gmail.com
          committer_name: malinkang
          committer_email: linkang.ma@gmail.com
      - name: telegram
        run: |
          python scripts/notion/telegram.py
