name: hugo sync
on:
  workflow_dispatch:
    inputs:
      content:
        description: 'content'
        required: false
  schedule:
    - cron: "0 0 * * *"
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ncm sync
        run: |
          python scripts/notion/ncm.py
      # - name: weread sync
      #   run: |
      #     python scripts/notion/weread.py "${{secrets.WEREAD_COOKIE}}"
      - name: ncm sync
        run: |
          python scripts/notion/ncm.py 
      - name: bilibili sync
        run: |
          python scripts/notion/bilibili.py 
      - name: hugo sync
        run: |
          python scripts/notion/hugo.py
      - name: telegram
        run: |
          python scripts/notion/telegram.py
      - name: commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: master
          author_name: malinkang
          author_email: linkang.ma@gmail.com
          committer_name: malinkang
          committer_email: linkang.ma@gmail.com
